site_name: CBIG
site_url: https://mfiorini9.github.io/
nav:
    - Home: index.md
    - Initiative overview: 
        - 'Background' : background.md
        - 'Standardized processing protocols' : SPP.md
        - 'Available data' : Available_data.md
    - Single-Cell RNA seq:
        - '10X Genomics' : scRNAseq_10X_Genomics.md
        - 'ParseBiosciences' : scRNAseq_ParseBio.md
    - Spatial RNA seq:     
        - 'Visium HD' : SpatialRNAseq_Visium_HD.md 
        - 'Visium' : SpatialRNAseq_Visium.md 
    - About:
        - 'Help and Feedback': contributing.md
        - 'Acknowledgement': Acknowledgement.md
        - 'License': 'LICENSE.md'
theme: readthedocs